### ISSUE TITLE
Error on nearly empty css sheet

### ISSUE THREAD

**Issue by dazlious** [thotzl/grunt-css-statistics#6]
I was getting "Cannot read property 'forEach' of undefined", when I ran grunt-css-statistics.

I figured out, that an error-handling was missing in:
*cssstats.js: getValueCount()*

Before calling a value.forEach-function, you should check, if values is undefined

```javascript
if (!values) {
    return arr;
}
```

My CSS looked this:

```javascript
@charset "UTF-8";

.mappedJS {
    * {
        box-sizing: border-box;
    }
}
```

After inserting it, all works fine

**Comment by thotzl** [comment]
thanks. i think i forget the error handling at this position. will fix it soon
